services:
  - type: web
    name: switchboard-rag
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OTHER_ENV_VAR
        value: YOUR_VALUE
